/**
 * A model printed as C++.
 *
 * The archive keeps a closed claim's model as a small declarative file: a chain
 * of named sections, a sample rate, and one map per parameter byte. This turns
 * that into code a reader can compile, and it is a rearrangement of the model in
 * exactly the sense the rest of this site is a rearrangement of the archive —
 * every constant, every section count and every structural choice below comes
 * out of the model file and nothing is added to it.
 *
 * **What is not the model's is the arithmetic.** The archive names its sections
 * in the words of the era it is reading — a first-order all-pass, a one-multiply
 * pole, the unit-slope shelving biquad of the audio cookbook — and says nothing
 * about how to write their difference equations, because that is not a fact
 * about the unit. The realisations here are the ordinary ones for the sections
 * named. The generated banner says so, on every example, so that a reader never
 * has to guess which half of the file a measurement stands behind.
 *
 * **A model whose shape this file does not know prints nothing.** Not a partial
 * chain, not a section left out with a comment where it was: a chain missing one
 * stage is a different effect, and an example that quietly dropped one would be
 * the site asserting something no record establishes. The reason is returned
 * instead, and the page shows the reason.
 */

import { asCpp, needsCmath, num, unreadable } from './model-maps.mjs';

/** Stage kinds with a realisation here. */
const STAGES = new Set(['allpass-chain', 'pole', 'shelf', 'peaking', 'gain']);

/**
 * One model as C++, or the reason there is none.
 *
 * @param {object} args
 * @param {any} args.model the parsed model file
 * @param {string} args.modelPath its path in the archive
 * @param {string} args.claimPath the inference file whose claim it closes
 * @param {any} args.reproduces that inference's `reproduces` block
 * @returns {{code: string} | {unsupported: string}}
 */
export function asExample({ model, modelPath, claimPath, reproduces }) {
  const kind = model?.model?.kind ?? null;
  try {
    if (kind === 'lti') return { code: lti({ model, modelPath, claimPath, reproduces }) };
    if (kind === 'table') return { code: tables({ model, modelPath, claimPath, reproduces }) };
    return {
      unsupported: `the model is of kind ${JSON.stringify(kind)}, which no example is generated from yet`,
    };
  } catch (error) {
    return { unsupported: error.message };
  }
}

/* -------------------------------------------------------------------------- */
/* The banner                                                                  */
/* -------------------------------------------------------------------------- */

/** @param {{model: any, modelPath: string, claimPath: string, reproduces: any}} args */
function banner({ model, modelPath, claimPath, reproduces }) {
  const meta = model.model ?? {};
  const lines = [
    '// ---------------------------------------------------------------------------',
    `// ${[meta.unit_id, meta.type, meta.class].filter(Boolean).join('  ·  ')}`,
    '//',
    `// Generated by yarn sync from ${modelPath}.`,
    `// The claim it closes: ${claimPath}`,
    '//',
    '// Every constant, every section count and every structural choice below is',
    "// the model's. The difference equations are the ordinary realisations of the",
    "// sections the model names — this site's arithmetic, not a measurement.",
  ];
  const domain = reproduces?.domain;
  if (domain) {
    if (domain.settings && Object.keys(domain.settings).length > 0) {
      lines.push('//', '// Compared against the unit over:');
      for (const [key, value] of Object.entries(domain.settings)) {
        lines.push(`//   ${key}: ${flatten(value)}`);
      }
    }
    if (Array.isArray(domain.stimulus) && domain.stimulus.length > 0) {
      lines.push(`//   stimulus: ${domain.stimulus.join(', ')}`);
    }
    if (typeof domain.outside === 'string') {
      lines.push('//', ...wrap(`Outside that domain this says nothing: ${domain.outside}`, '// '));
    }
  }
  const residual = reproduces?.residual;
  if (residual && typeof residual.median === 'number') {
    lines.push(
      '//',
      `// Residual: ${residual.median} median, ${residual.worst} worst, in ${residual.unit}.`,
    );
  }
  lines.push('// ---------------------------------------------------------------------------');
  return lines.join('\n');
}

/** @param {any} value */
function flatten(value) {
  if (Array.isArray(value)) return value.map(flatten).join(', ');
  if (value && typeof value === 'object') {
    return Object.entries(value)
      .map(([key, held]) => `${key} ${flatten(held)}`)
      .join('; ');
  }
  return String(value);
}

/**
 * Wrap prose to something a terminal can hold.
 *
 * Eighty-eight rather than the usual eighty: the tables in these files run to
 * two hundred characters and the block scrolls anyway, so a comment set to a
 * third of the width the code beside it takes reads as a different document.
 * @param {string} text @param {string} prefix
 */
function wrap(text, prefix, width = 88) {
  /** @type {string[]} */
  const lines = [];
  let line = '';
  for (const word of text.split(/\s+/)) {
    if (line && `${line} ${word}`.length > width) {
      lines.push(prefix + line);
      line = word;
    } else {
      line = line ? `${line} ${word}` : word;
    }
  }
  if (line) lines.push(prefix + line);
  return lines;
}

/* -------------------------------------------------------------------------- */
/* Names                                                                       */
/* -------------------------------------------------------------------------- */

/** `roland-sc8850-01` → `roland_sc8850_01`; `01 20` → `type_01_20`. */
function identifier(text) {
  return String(text)
    .trim()
    .replace(/[^0-9A-Za-z]+/g, '_')
    .replace(/^_+|_+$/g, '')
    .replace(/^(\d)/, '_$1');
}

/** The namespace an example lives in, so two types can be included together. */
function namespaceOf(model) {
  const meta = model.model ?? {};
  const parts = ['soundings'];
  if (meta.unit_id) parts.push(identifier(meta.unit_id));
  if (meta.type) parts.push(`type_${bare(meta.type)}`);
  else if (meta.class) parts.push(identifier(meta.class));
  return parts.join('::');
}

/** The same without the leading-digit guard, for use after a prefix. */
function bare(text) {
  return String(text)
    .trim()
    .replace(/[^0-9A-Za-z]+/g, '_')
    .replace(/^_+|_+$/g, '');
}

/** `40 03 03` → `b40_03_03`, which is what the byte is called in the code. */
function byteName(address) {
  return `b${bare(address)}`;
}

/** `corner_hz` → `CornerHz`. */
function camel(text) {
  return String(text)
    .split(/[^0-9A-Za-z]+/)
    .filter(Boolean)
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join('');
}

/* -------------------------------------------------------------------------- */
/* An LTI chain                                                                */
/* -------------------------------------------------------------------------- */

/** @param {{model: any, modelPath: string, claimPath: string, reproduces: any}} args */
function lti(args) {
  const { model } = args;
  const chain = model.chain;
  if (!Array.isArray(chain) || chain.length === 0) throw new Error('the model has no chain');
  if (typeof model.sample_rate_hz !== 'number') {
    throw new Error('the model names no sample rate, and every section here is clocked by one');
  }
  for (const stage of chain) {
    if (!STAGES.has(stage.kind)) {
      throw new Error(
        `the chain holds a ${JSON.stringify(stage.kind)} section, which has no realisation here`,
      );
    }
  }

  /** @type {{name: string, address: string}[]} */
  const bytes = [];
  /** @type {string[]} */
  const maps = [];
  /** @type {Set<string>} */
  const helpers = new Set();
  let cmath = true; // every realisation here needs tan or exp

  /** One parameter: a constant, or a function of a byte. */
  const parameter = (stage, index, key) => {
    const value = stage[key];
    if (typeof value === 'number') return { constant: num(value) };
    if (value && typeof value === 'object' && typeof value.fixed === 'number') {
      return { constant: num(value.fixed), why: value.why ?? null };
    }
    if (value && typeof value === 'object' && value.map) {
      const why = unreadable(value.map);
      if (why) throw new Error(`${stage.kind}.${key} carries ${why}`);
      const name = `${stage.kind.replace(/-\w/g, (m) => m[1].toUpperCase())}${index}${camel(key)}`;
      maps.push(asCpp(value.map, name));
      if (needsCmath(value.map)) cmath = true;
      if (value.byte && !bytes.some((entry) => entry.address === value.byte)) {
        bytes.push({ name: byteName(value.byte), address: value.byte });
      }
      return { call: `${name}(${value.byte ? byteName(value.byte) : 'byte'})` };
    }
    return null;
  };

  /** @type {string[]} */
  const members = [];
  /** @type {string[]} */
  const prepare = [];
  /** @type {string[]} */
  const process = [];

  chain.forEach((stage, index) => {
    switch (stage.kind) {
      case 'allpass-chain':
        helpers.add('allpass').add('dcblock');
        allpassStage({ stage, index, parameter, members, prepare, process });
        break;
      case 'pole':
        helpers.add('onepole');
        poleStage({ stage, index, parameter, members, prepare, process });
        break;
      case 'shelf':
        helpers.add(stage.order === 2 ? 'biquad' : 'shelf1');
        shelfStage({ stage, index, parameter, members, prepare, process });
        break;
      case 'peaking':
        helpers.add('biquad');
        peakingStage({ stage, index, parameter, members, prepare, process });
        break;
      case 'gain':
        gainStage({ stage, index, parameter, members, prepare, process });
        break;
      default:
        throw new Error(`no realisation for ${stage.kind}`);
    }
  });

  const ns = namespaceOf(model);
  const rate = num(model.sample_rate_hz);
  const out = [banner(args), ''];
  if (cmath) out.push('#include <cmath>', '');
  out.push(`namespace ${ns} {`, '');
  if (typeof model.why_this_rate === 'string') {
    out.push(...wrap(model.why_this_rate, '// '));
  }
  out.push(`constexpr double kSampleRateHz = ${rate};`);
  out.push(PI, '');
  for (const helper of ['allpass', 'dcblock', 'onepole', 'shelf1', 'biquad']) {
    if (helpers.has(helper)) out.push(HELPERS[helper], '');
  }
  for (const map of maps) out.push(map, '');
  out.push('/** The chain the model names, in the order it names it. */');
  out.push('struct Effect {');
  out.push(...members.map((line) => `  ${line}`));
  out.push('');
  out.push(`  void prepare(${bytes.map((entry) => `int ${entry.name}`).join(', ') || 'void'}) {`);
  out.push(...prepare.map((line) => `    ${line}`));
  out.push('  }');
  out.push('');
  out.push('  double process(double x) {');
  out.push(...process.map((line) => `    ${line}`));
  out.push('    return x;');
  out.push('  }');
  out.push('};');
  out.push('');
  out.push(`}  // namespace ${ns}`);
  return out.join('\n');
}

/** @param {any} args */
function allpassStage({ stage, index, parameter, members, prepare, process }) {
  if (stage.feedback_around || stage.feedback_sections) {
    throw new Error(
      'the loop is taken around part of the cascade, and where it is tapped decides what the ' +
        'effect is — no example is printed from a tap point this file would have to guess',
    );
  }
  const sections = stage.sections;
  if (typeof sections !== 'number') throw new Error('the all-pass chain names no section count');
  const corner = parameter(stage, index, 'corner_hz');
  const mix = parameter(stage, index, 'mix');
  if (!corner || !mix) throw new Error('the all-pass chain names no corner or no mix');
  const feedback = stage.feedback === undefined ? null : parameter(stage, index, 'feedback');
  if (stage.feedback !== undefined && !feedback) {
    throw new Error('the all-pass chain carries a feedback the map reader could not read');
  }
  if (stage.q)
    throw new Error(
      'an all-pass section with a Q is a second-order one, which has no realisation here',
    );

  members.push(`Allpass1 allpass${index}[${sections}];`);
  members.push(`double mix${index} = 0.0;`);
  if (feedback) {
    members.push(`double feedback${index} = 0.0;`);
    members.push(`double loop${index} = 0.0;`);
    members.push(`DcBlock block${index};`);
  }

  prepare.push(`const double corner${index} = ${corner.call ?? corner.constant};`);
  prepare.push(`for (Allpass1& section : allpass${index}) section.setCornerHz(corner${index});`);
  prepare.push(`mix${index} = ${mix.call ?? mix.constant};`);
  if (feedback) {
    prepare.push(`feedback${index} = ${feedback.call ?? feedback.constant};`);
    if (typeof stage.feedback_highpass_hz === 'number') {
      prepare.push(`block${index}.setCornerHz(${num(stage.feedback_highpass_hz)});`);
    }
  }

  if (feedback) {
    const delay = stage.feedback_delay ?? 0;
    if (delay !== 1) {
      throw new Error(
        `the loop is ${delay} sample(s) late, and only a one-sample loop has a realisation here`,
      );
    }
    process.push('// The loop returns one sample late and through a block at DC, which is what');
    process.push('// the model names. The cascade is summed with the dry, never averaged with it.');
    process.push(
      `double wet${index} = x + feedback${index} * block${index}.process(loop${index});`,
    );
  } else {
    process.push(`double wet${index} = x;`);
  }
  process.push(
    `for (Allpass1& section : allpass${index}) wet${index} = section.process(wet${index});`,
  );
  if (feedback) process.push(`loop${index} = wet${index};`);
  process.push(`x = x + mix${index} * wet${index};`);
}

/** @param {any} args */
function poleStage({ stage, index, parameter, members, prepare, process }) {
  if (stage.q) {
    throw new Error(
      'a pole with a Q is a conjugate pair rather than a single pole, and no example is printed ' +
        'from one here',
    );
  }
  const side = stage.side;
  if (side !== 'low' && side !== 'high') throw new Error(`a pole on side ${JSON.stringify(side)}`);
  // A model that names no form means the ordinary bilinear-transformed pole: the
  // archive's own catalogue holds the cheap one as a separate candidate, under
  // its own name, so the unqualified reading is not ambiguous.
  const form = stage.form ?? 'bilinear';
  if (form !== 'bilinear' && form !== 'one-multiply') {
    throw new Error(`a pole written in the ${JSON.stringify(form)} form`);
  }
  const corner = parameter(stage, index, 'corner_hz');
  const sections = parameter(stage, index, 'sections');
  if (!corner || !sections) throw new Error('the pole names no corner or no section count');

  const cap = 8;
  members.push(`OnePole pole${index}[${cap}];`);
  members.push(`int poleCount${index} = 0;`);
  prepare.push(`poleCount${index} = static_cast<int>(${sections.call ?? sections.constant});`);
  prepare.push(`if (poleCount${index} > ${cap}) poleCount${index} = ${cap};`);
  prepare.push(`const double poleCorner${index} = ${corner.call ?? corner.constant};`);
  prepare.push(`for (int i = 0; i < poleCount${index}; ++i) {`);
  prepare.push(
    `  pole${index}[i].set(poleCorner${index}, OnePole::Side::${side === 'low' ? 'Low' : 'High'}, OnePole::Form::${form === 'one-multiply' ? 'OneMultiply' : 'Bilinear'});`,
  );
  prepare.push('}');
  process.push(`for (int i = 0; i < poleCount${index}; ++i) x = pole${index}[i].process(x);`);
}

/** @param {any} args */
function shelfStage({ stage, index, parameter, members, prepare, process }) {
  const side = stage.side;
  if (side !== 'low' && side !== 'high') throw new Error(`a shelf on side ${JSON.stringify(side)}`);
  const order = stage.order;
  if (order !== 1 && order !== 2) throw new Error(`a shelf of order ${JSON.stringify(order)}`);
  const corner = parameter(stage, index, 'corner_hz');
  const gain = parameter(stage, index, 'gain_db');
  if (!corner || !gain) throw new Error('the shelf names no corner or no gain');

  if (order === 1) {
    members.push(`Shelf1 shelf${index};`);
    prepare.push(
      `shelf${index}.set(${corner.call ?? corner.constant}, ${gain.call ?? gain.constant}, Shelf1::Side::${side === 'low' ? 'Low' : 'High'});`,
    );
    process.push(`x = shelf${index}.process(x);`);
    return;
  }
  members.push(`Biquad shelf${index};`);
  prepare.push(
    `shelf${index}.setShelf(${corner.call ?? corner.constant}, ${gain.call ?? gain.constant}, Biquad::Side::${side === 'low' ? 'Low' : 'High'});`,
  );
  process.push(`x = shelf${index}.process(x);`);
}

/** @param {any} args */
function peakingStage({ stage, index, parameter, members, prepare, process }) {
  const centre = parameter(stage, index, 'centre_hz');
  const gain = parameter(stage, index, 'gain_db');
  const q = parameter(stage, index, 'q');
  if (!centre || !gain || !q) throw new Error('the peaking section names no centre, gain or Q');
  members.push(`Biquad peaking${index};`);
  prepare.push(
    `peaking${index}.setPeaking(${centre.call ?? centre.constant}, ${gain.call ?? gain.constant}, ${q.call ?? q.constant});`,
  );
  process.push(`x = peaking${index}.process(x);`);
}

/** @param {any} args */
function gainStage({ stage, index, parameter, members, prepare, process }) {
  const gain = parameter(stage, index, 'gain_db');
  if (!gain) throw new Error('the gain section names no gain');
  members.push(`double gain${index} = 1.0;`);
  prepare.push(`gain${index} = std::pow(10.0, (${gain.call ?? gain.constant}) / 20.0);`);
  process.push(`x *= gain${index};`);
}

/* -------------------------------------------------------------------------- */
/* The sections                                                                */
/* -------------------------------------------------------------------------- */

/** Not every standard library defines M_PI, and this file has to compile where it lands. */
const PI = 'constexpr double kPi = 3.14159265358979323846;';

const HELPERS = {
  allpass: `/**
 * One first-order all-pass section: unit gain at every frequency, and a phase
 * that runs from nothing to half a turn through the corner. Bilinear-transformed,
 * so the corner is prewarped and sits where it is asked for.
 */
struct Allpass1 {
  double a = 0.0, x1 = 0.0, y1 = 0.0;

  void setCornerHz(double hz) {
    const double k = std::tan(kPi * hz / kSampleRateHz);
    a = (k - 1.0) / (k + 1.0);
  }

  double process(double x) {
    const double y = a * x + x1 - a * y1;
    x1 = x;
    y1 = y;
    return y;
  }
};`,

  dcblock: `/** A one-pole high-pass, which is what blocking a loop at DC comes to. */
struct DcBlock {
  double r = 0.0, x1 = 0.0, y1 = 0.0;

  void setCornerHz(double hz) { r = std::exp(-2.0 * kPi * hz / kSampleRateHz); }

  double process(double x) {
    const double y = x - x1 + r * y1;
    x1 = x;
    y1 = y;
    return y;
  }
};`,

  onepole: `/**
 * A single pole, written either of the two ways the archive tells apart.
 *
 * \`Bilinear\` is the transformed pole, which carries a zero at half the rate.
 * \`OneMultiply\` is the cheapest a fixed-point part can write one — one multiply,
 * one state, and no zero — and the archive holds the two as separate candidates
 * because their skirts differ where it can read them.
 */
struct OnePole {
  enum class Side { Low, High };
  enum class Form { Bilinear, OneMultiply };

  Side side = Side::Low;
  Form form = Form::Bilinear;
  double a = 0.0, c = 0.0, k = 0.0, x1 = 0.0, y1 = 0.0, state = 0.0;

  void set(double hz, Side which, Form how) {
    side = which;
    form = how;
    if (how == Form::OneMultiply) {
      k = 1.0 - std::exp(-2.0 * kPi * hz / kSampleRateHz);
      return;
    }
    const double t = std::tan(kPi * hz / kSampleRateHz);
    c = (1.0 - t) / (1.0 + t);
    a = which == Side::Low ? t / (1.0 + t) : 1.0 / (1.0 + t);
  }

  double process(double x) {
    if (form == Form::OneMultiply) {
      state += k * (x - state);
      return side == Side::Low ? state : x - state;
    }
    const double y = side == Side::Low ? a * (x + x1) + c * y1 : a * (x - x1) + c * y1;
    x1 = x;
    y1 = y;
    return y;
  }
};`,

  shelf1: `/**
 * A first-order shelf: one pole, one zero, tilting the two sides of its corner
 * against each other. \`(s + w0 * V) / (s + w0)\` for a low shelf and
 * \`(V * s + w0) / (s + w0)\` for a high one, bilinear-transformed.
 */
struct Shelf1 {
  enum class Side { Low, High };

  double b0 = 1.0, b1 = 0.0, a1 = 0.0, x1 = 0.0, y1 = 0.0;

  void set(double hz, double gainDb, Side side) {
    const double v = std::pow(10.0, gainDb / 20.0);
    const double k = std::tan(kPi * hz / kSampleRateHz);
    const double norm = 1.0 / (1.0 + k);
    a1 = (k - 1.0) * norm;
    if (side == Side::Low) {
      b0 = (1.0 + v * k) * norm;
      b1 = (v * k - 1.0) * norm;
    } else {
      b0 = (v + k) * norm;
      b1 = (k - v) * norm;
    }
  }

  double process(double x) {
    const double y = b0 * x + b1 * x1 - a1 * y1;
    x1 = x;
    y1 = y;
    return y;
  }
};`,

  biquad: `/** A second-order section, set the way the audio cookbook sets one. */
struct Biquad {
  enum class Side { Low, High };

  double b0 = 1.0, b1 = 0.0, b2 = 0.0, a1 = 0.0, a2 = 0.0;
  double x1 = 0.0, x2 = 0.0, y1 = 0.0, y2 = 0.0;

  void setShelf(double hz, double gainDb, Side side) {
    const double a = std::pow(10.0, gainDb / 40.0);
    const double w = 2.0 * kPi * hz / kSampleRateHz;
    const double cs = std::cos(w);
    // Unit slope, which is what \`order 2\` means here.
    const double alpha = std::sin(w) / 2.0 * std::sqrt(2.0);
    const double two = 2.0 * std::sqrt(a) * alpha;
    const double sign = side == Side::Low ? 1.0 : -1.0;
    const double a0 = (a + 1.0) - sign * (a - 1.0) * cs + two;
    b0 = a * ((a + 1.0) + sign * (a - 1.0) * cs + two) / a0;
    b1 = sign * 2.0 * a * ((a - 1.0) + sign * (a + 1.0) * cs) / a0;
    b2 = a * ((a + 1.0) + sign * (a - 1.0) * cs - two) / a0;
    a1 = -sign * 2.0 * ((a - 1.0) - sign * (a + 1.0) * cs) / a0;
    a2 = ((a + 1.0) - sign * (a - 1.0) * cs - two) / a0;
  }

  void setPeaking(double hz, double gainDb, double q) {
    const double a = std::pow(10.0, gainDb / 40.0);
    const double w = 2.0 * kPi * hz / kSampleRateHz;
    const double alpha = std::sin(w) / (2.0 * q);
    const double a0 = 1.0 + alpha / a;
    b0 = (1.0 + alpha * a) / a0;
    b1 = -2.0 * std::cos(w) / a0;
    b2 = (1.0 - alpha * a) / a0;
    a1 = b1;
    a2 = (1.0 - alpha / a) / a0;
  }

  double process(double x) {
    const double y = b0 * x + b1 * x1 + b2 * x2 - a1 * y1 - a2 * y2;
    x2 = x1;
    x1 = x;
    y2 = y1;
    y1 = y;
    return y;
  }
};`,
};

/* -------------------------------------------------------------------------- */
/* A model that is a table                                                     */
/* -------------------------------------------------------------------------- */

/**
 * The byte at an address, and what it stands for.
 *
 * Several classes closed on a table rather than on a chain: a delay time, a
 * modulation rate, a rotor's acceleration. For those the table *is* the
 * algorithm, and which of several tables applies is chosen by the range the
 * document prints against the address — so the example carries the printed range
 * as the key, exactly as the archive does.
 * @param {{model: any, modelPath: string, claimPath: string, reproduces: any}} args
 */
function tables(args) {
  const { model } = args;
  const held = model.tables;
  if (!held || typeof held !== 'object' || Object.keys(held).length === 0) {
    throw new Error('the model holds no tables');
  }

  const ns = namespaceOf(model);
  const out = [banner(args), ''];
  let cmath = false;
  /** @type {string[]} */
  const functions = [];
  /** @type {[string, string][]} */
  const dispatch = [];

  for (const [range, table] of Object.entries(held)) {
    const why = unreadable(table);
    if (why) throw new Error(`the table printed against ${JSON.stringify(range)} is ${why}`);
    const name = `at${camel(identifier(range))}`;
    functions.push(`// printed range: ${range}`);
    if (typeof table.why_it_ends_early === 'string') {
      functions.push(...wrap(table.why_it_ends_early, '// '));
    }
    functions.push(asCpp(table, name));
    functions.push('');
    if (needsCmath(table)) cmath = true;
    dispatch.push([range, name]);
  }

  if (cmath) out.push('#include <cmath>', '');
  out.push('#include <cstring>', '');
  out.push(`namespace ${ns} {`, '');
  if (typeof model.what === 'string') out.push(...wrap(model.what, '// '), '');
  out.push(...functions);

  out.push('/**');
  out.push(' * Which table applies is decided by the range the page prints against the');
  out.push(' * address, which is a fact about the document rather than about the byte.');
  out.push(' */');
  out.push('inline bool lookUp(const char* printedRange, int byte, double& out) {');
  for (const [range, name] of dispatch) {
    out.push(
      `  if (std::strcmp(printedRange, ${JSON.stringify(range)}) == 0) { out = ${name}(byte); return true; }`,
    );
  }
  out.push('  // A range no reading has been taken over. Saying nothing is the answer:');
  out.push('  // returning a neighbouring table would be inventing a measurement.');
  out.push('  return false;');
  out.push('}');

  const arrival = model.arrival;
  if (arrival && typeof arrival === 'object') {
    out.push('');
    out.push('// The model also records where the quantity comes to rest, as figures rather');
    out.push('// than as a rule: what it is that reaches them is stated in the claim and is');
    out.push('// not written out here, because the condition is not in the model file.');
    for (const [key, value] of Object.entries(arrival)) {
      if (typeof value === 'number') {
        out.push(`inline constexpr double k${camel(key)} = ${num(value)};`);
      } else if (typeof value === 'string') {
        out.push(`// ${key}: ${value}`);
      }
    }
  }

  out.push('');
  out.push(`}  // namespace ${ns}`);
  return out.join('\n');
}
